"""
AtmoSync AI - Reports API

Provides the status of the reporting module responsible for
generating dashboard and analytics reports.
"""

from __future__ import annotations

from fastapi import APIRouter, status

router = APIRouter(
    tags=["Reports"],
)


@router.get(
    "/reports/status",
    summary="Reports Module Status",
    description="Returns the current status of the reporting module.",
    status_code=status.HTTP_200_OK,
)
def reports_status() -> dict[str, object]:
    return {
        "success": True,
        "status": "available",
        "message": "Reports are generated by the analytics pipeline.",
        "generation_mode": "pipeline",
    }