/**
 * ReportTable
 *
 * Responsive table layout for placeholder report rows.
 * Semantic markup: caption, thead, tbody.
 */
function ReportTable() {
  const rows = [
    {
      reportName: "—",
      type: "—",
      region: "—",
      generatedBy: "—",
      generatedDate: "—",
      status: "—",
      export: "—",
    },
    {
      reportName: "—",
      type: "—",
      region: "—",
      generatedBy: "—",
      generatedDate: "—",
      status: "—",
      export: "—",
    },
    {
      reportName: "—",
      type: "—",
      region: "—",
      generatedBy: "—",
      generatedDate: "—",
      status: "—",
      export: "—",
    },
    {
      reportName: "—",
      type: "—",
      region: "—",
      generatedBy: "—",
      generatedDate: "—",
      status: "—",
      export: "—",
    },
  ];

  return (
    <section className="report-table" aria-labelledby="report-table-title">
      <header className="report-table__header">
        <h2
          id="report-table-title"
          className="report-table__title"
        >
          Report Table
        </h2>

        <p className="report-table__description">
          Placeholder table for AI-generated climate intelligence reports.
        </p>
      </header>

      <div className="report-table__wrapper">
        <table className="table report-table__table" aria-label="Reports">
          <caption className="report-table__caption">
            Listing of generated reports with export availability.
          </caption>

          <thead>
            <tr>
              <th scope="col">Report Name</th>
              <th scope="col">Type</th>
              <th scope="col">Region</th>
              <th scope="col">Generated By</th>
              <th scope="col">Generated Date</th>
              <th scope="col">Status</th>
              <th scope="col">Export</th>
            </tr>
          </thead>

          <tbody>
            {rows.map((row, index) => (
              <tr key={`report-row-${index}`}>
                <td>{row.reportName}</td>
                <td>{row.type}</td>
                <td>{row.region}</td>
                <td>{row.generatedBy}</td>
                <td>{row.generatedDate}</td>
                <td>{row.status}</td>
                <td>{row.export}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}

export default ReportTable;

